Update documentation.md
elixirschool/elixirschool pull request #2356
Opened 2020-08-16 05:14 UTC by felipericieri

Hey folks 👋
Great work on the Elixir School!
I’ve found some typos in the docs, as follows.

...
Corrects typos, grammar and suggests format

2020-08-16 10:56 UTC, tajchumber commented on en/lessons/basics/documentation.md
> +It is worth nothing at this point that you change the markup tool to Cmark if you wish, but you will need to do a little more configuration which you can read about [here](https://hexdocs.pm/ex_doc/E
`noting` is the correct word here

2020-08-18 13:12 UTC, doomspork commented on en/lessons/basics/documentation.md
> +It is worth nothing at this point that you change the markup tool to Cmark if you wish, but you will need to do a little more configuration which you can read about [here](https://hexdocs.pm/ex_doc/E
```suggestion
It is worth nothing at this point that you change the markup tool to Cmark if you wish, but you will need to do a little more configuration which you can read about [here](https://hexdocs.pm/ex_doc/ExDoc.Markdown.html#module-using-cmark).
```

2020-08-18 13:13 UTC, doomspork commented on en/lessons/basics/documentation.md
> +It is worth nothing at this point that you change the markup tool to Cmark if you wish, but you will need to do a little more configuration which you can read about [here](https://hexdocs.pm/ex_doc/E
As @tajchumber mentioned, `noting` is the correct word here. We are taking note.

2020-09-03 03:44 UTC, doomspork requested changes

2020-09-03 03:44 UTC, doomspork commented on en/lessons/basics/documentation.md
> +It is worth nothing at this point that you change the markup tool to Cmark if you wish, but you will need to do a little more configuration which you can read about [here](https://hexdocs.pm/ex_doc/E
```suggestion
It is worth noting at this point that you change the markup tool to Cmark if you wish, but you will need to do a little more configuration which you can read about [here](https://hexdocs.pm/ex_doc/ExDoc.Markdown.html#module-using-cmark).
```

2020-09-03 03:44 UTC, doomspork approved these changes

2020-09-03 03:45 UTC, merged