Update collections.md
elixirschool/elixirschool pull request #2429
Opened 2020-10-10 00:10 UTC by hackvan

Correcciones de palabras incompletas y gramaticales (tildes).

2020-10-10 00:23 UTC, erickgnavar requested changes

2020-10-10 00:23 UTC, erickgnavar commented on es/lessons/basics/collections.md
> +version: 1.3.2
La versión debería quedarse en la `1.3.1` ya que es la misma versión de contenido en inglés, las versiones se usan para hacer match y poder mostrar en la web si un artículo esta a la par de la versión en inglés

2020-10-12 00:00 UTC, hackvan commented on es/lessons/basics/collections.md
> +version: 1.3.2
Listo, leí en la guía de contribuciones que por motivos gramaticales se aumentaba el número del patch version, creo que lo mal entendi, ya quedó nuevamente en la version `1.3.1`.

2020-10-12 13:34 UTC, erickgnavar approved these changes

2020-10-12 13:35 UTC, merged