[GR] fully translates ecto/associations
elixirschool/elixirschool pull request #2457
Opened 2020-10-24 17:13 UTC by gemantzu

2020-10-26 13:15 UTC, Kosmas requested changes

2020-10-26 13:15 UTC, Kosmas commented on gr/lessons/ecto/associations.md
> +Σε αυτό τον τομέα θα μάθουμε πως να χρησιμοποιήσουμε το Ecto για να ορίσουμε και να εργαστούμε με συσχετίσεις ανάμεσα στα σχήματά μας.
@gemantzu the title is 'συσχετισμοί', but you are using 'συσχετίσεις' here.
Wouldn't it be better if one of them is used?

2020-10-26 13:15 UTC, Kosmas commented on gr/lessons/ecto/associations.md
> +Θα ξεκινήσουμε με τύο σχήματα: Τα `Movie` και `Character`.
'τύο' -> 'δύο'

2020-10-26 13:15 UTC, Kosmas commented on gr/lessons/ecto/associations.md
> +Τώρα είμαστε έτοιμοι να χτήσουμε τη μετατροπή και το σχήμα για το `Character`.
'χτήσουμε' -> 'χτίσουμε'

2020-10-26 13:15 UTC, Kosmas commented on gr/lessons/ecto/associations.md
> +Θα ορίσουμε τη μετατορπή μας ώστε να έχει δύο ξένα κλειδιά.
'μετατορπή' -> 'μετατροπή'

2020-10-26 13:15 UTC, Kosmas commented on gr/lessons/ecto/associations.md
> +Τώρα θα χτίσουμε ένα συσσχετιζόμενο χαρακτήρα και θα τον εισάγουμε στη βάση δεδομένων:
'συσσχετιζόμενο' -> 'συσχετιζόμενο'

2020-10-26 13:15 UTC, Kosmas commented on gr/lessons/ecto/associations.md
> +Θα μιλήσουμε περισσότερο για την προφόρτωση δεδομένω σε λίγο.
'δεδομένω' -> 'δεδομένων'

2020-10-26 18:28 UTC, gemantzu commented
Thanks for the review @Kosmas ! All fixed!

2020-10-26 20:37 UTC, RTSolo commented on gr/lessons/ecto/associations.md
> +Θα ξεκινήσουμε με την ίδια εφαρμογή `Friends` από τα προηγούμενα μαθήματα.
το προηγούμενο μάθημα.

2020-10-26 20:48 UTC, RTSolo commented on gr/lessons/ecto/associations.md
> +Παρόμοια το σχήμα μας χρειάζεται να ορίσουμε τη σχέση "ανήκει σε" ανάμεσα σε ένα χαρακτήρα και την ταινία του.
να προσδιορίζει την σχέση (;)

2020-10-26 21:00 UTC, RTSolo commented on gr/lessons/ecto/associations.md
> +* Η δομή της εγγραφής που θέλουμε να αποθηκεύσουμε.
Τη δομή

2020-10-26 21:06 UTC, RTSolo commented on gr/lessons/ecto/associations.md
> +Για να μπορέσουμε να αποθηκεύσουμε το διανομέα μιας ταινίας, θα έχουμε την ίδια προσέγγιση περνώντας το _όνομα_ της σχέσης της ταινίας με το διανομέα σαν δεύτερο όρισμα της `build_assoc/3`:
Για να μπορέσουμε να αποθηκεύσουμε το διανομέα μιας ταινίας με την χρήση της `build_assoc/3`,

2020-10-26 21:12 UTC, RTSolo commented on gr/lessons/ecto/associations.md
> +Αντί να περάσουμε μια _αποθηκευμένη_ δομή ηθοποιού στην `put_assoc/4`, απλά περνάμε ένα χάρτη με τα στοιχεία νέου ηθοποιού που θέλουμε να δημιουργήσουμε:
, απλά περνάμε μια δομή με

2020-10-26 21:13 UTC, RTSolo commented on gr/lessons/ecto/associations.md
> +Στην επόμενη ενότητα, θα μάθουμε πως να δημιουργούμε ερωτήματα των συσχετιζόμενων εγγραφών μας.
ερωτήματα για τις συσχετιζόμενες εγγραφές μας. (;)

2020-10-26 21:17 UTC, gemantzu commented on gr/lessons/ecto/associations.md
> +Θα ξεκινήσουμε με την ίδια εφαρμογή `Friends` από τα προηγούμενα μαθήματα.
δεν το μετέφρασα ακριβώς, καθώς η εφαρμογή είναι και στα δύο προηγούμενα μαθήματα.

2020-10-26 21:20 UTC, gemantzu commented on gr/lessons/ecto/associations.md
> +Παρόμοια το σχήμα μας χρειάζεται να ορίσουμε τη σχέση "ανήκει σε" ανάμεσα σε ένα χαρακτήρα και την ταινία του.
`Παρόμοια το σχήμα μας θα πρέπει να ορίζει τη σχέση "ανήκει σε" ανάμεσα σε ένα χαρακτήρα και την ταινία του.` Το βρίσκω λίγο καλύτερο σε σχέση με τα συμφραζόμενα.

2020-10-26 21:26 UTC, gemantzu commented on gr/lessons/ecto/associations.md
> +Αντί να περάσουμε μια _αποθηκευμένη_ δομή ηθοποιού στην `put_assoc/4`, απλά περνάμε ένα χάρτη με τα στοιχεία νέου ηθοποιού που θέλουμε να δημιουργήσουμε:
όχι, ο χάρτης είναι σωστός εδώ.

2020-10-26 21:26 UTC, gemantzu commented on gr/lessons/ecto/associations.md
> +Στην επόμενη ενότητα, θα μάθουμε πως να δημιουργούμε ερωτήματα των συσχετιζόμενων εγγραφών μας.
Καλύτερα νομίζω. Thanks

2020-10-26 21:35 UTC, gemantzu commented
Thanks @RTSolo. Accomodated most of the suggestions.

2020-10-27 19:57 UTC, doomspork approved these changes

2020-10-27 19:57 UTC, merged