[GR] Bump benchee to latest version
elixirschool/elixirschool pull request #2483
Opened 2020-10-30 19:36 UTC by RTSolo

2020-10-30 20:01 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Με μια πρώτη ματιά, ο τομές `Comparison` μας δείχνει ότι η εκδοχή μας της `map.flatten` είναι 1.94x φορές πιο αργή από την `flat_map`.
τομέας

2020-10-30 20:02 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +* **ips** - σημαίνει "iterations per second - επαναλήψεις το δευτερόλεπτο", το οποίο μας λέει πόσο συχνά η δωθείσα συνάρτηση μπορεί να εκτελεστεί σε ένα δευτερόλεπτο.
δοθείσα.

2020-10-30 20:02 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +* **average** - είναι ο μέσος χρόνος εκτέλεσης της δωθείσας συνάρτησης.
δοθείσας

2020-10-30 20:03 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Εξ' αιτίας περιβαλοντικών ανακολουθιών αυτή η τιμή θα είναι πιο σταθερή από την `average`, και πιο ικανή να αντικατοπτρίσει την κανονική απόδοση του κώδικά σας στην παραγωγή.
περιβαλλοντικών

2020-10-30 20:04 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Υπάρχουν επίσης άλλα διαθέσιμα στατιστικά, αλλά αυτές οι τέσσερις είναι συχνά οι πιό χρήσιμες και συχνά χρησιμοποιούμενες για συγκριτικές αξιολογήσεις, γιαυτό και εμφανίζονται στον προκαθορισμένο μορ
γι' αυτό

2020-10-30 20:05 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Στην πιο συχνή διεπαφή `Benchee.run/2`, αυτές περνάνε ως το δεύτερο όρισμα στη μορφή μιας προαιρετικής λίστας λέξεων κλειδί:
λέξεων κλειδιά
NOTETOSELF: πρέπει να το αλλάξουμε και αλλού λογικά αυτό...

2020-10-30 20:08 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Αυτό σας δίνει περισσότερα δεδομένα στον ίδιο χρόνο, αλλά επίσης βάζει ένα φόρτο στο σύστημά σας ο οποίος παρεμβάλεται στα αποτελέσματα των συγκριτικών αξιολογήσεων.
παρεμβάλλεται

2020-10-30 20:08 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +* **measure_function_call_overhead** - μετράει πόσο χόνο χρειάζεται μια κλήση κενής συνάρτησης και το αφαιρεί κάθε φορά από τον χρόνο εκτέλεσης.
χρόνο

2020-10-30 20:09 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Αυτό μπορεί να μας κερδίσει σρόνο κατά την δημιουργία των `suits` σας.
χρόνο

2020-10-30 20:13 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Δείτε το [Αποθηκεύοντας & Φορτώνοντας στα Benchee docs](//github.com/bencheeorg/benchee#saving-loading-and-comparing-previous-runs).
Δείτε το [Saving & Loading στην τεκμηρίωση του Benchee].

2020-10-30 20:13 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Δείτε το [Αποθηκεύοντας & Φορτώνοντας στα Benchee docs](//github.com/bencheeorg/benchee#saving-loading-and-comparing-previous-runs).
Δες πιο πάνω

2020-10-30 20:14 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +* **print** - ένας χάρτης ή μια λίστα λέξεων κλειδί με τις ακόλουθες επιλογές σαν άτομα για τα κλειδιά και τιμές είτε `true` ή `false`.
λέξεων κλειδιά

2020-10-30 20:15 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Η στρατηγική κλιμάκωσης μονάδας καθορίζει πως το Benchee επιλέγει την καλύτερη μονάδα για μια μεγάλη λίστα τιμών, όταν οι επι μέρους τιμές στη λίστα έχουν πολλά διαφορετικές ιδανικές μονάδες μέτρησης
πολλές διαφορετικές

2020-10-30 20:17 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Μπορείτε να δείτο το [ένα παράδειγμα html αναφοράς](http://www.pragtob.info/benchee/README/results.html) αν σας ενδιαφέρει, περιέχει γραφήματα σαν αυτό:
δείτε το

2020-10-30 20:19 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Προς το παρόν δεν μπορεί να ιχνηλατήσει την κατανάλωση μνήμης σε άλλες διεργασίες (όπως οι ίστες εργατών).
λίστες εργατών

2020-10-30 20:19 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Όπως μπορείτε να δείτε, το Benchee δεν θα εμφανίσει όλα τα στατηστικά αφού όλα τα δείγματα που πάρθηκαν ήταν ίδια.
στατιστικά

2020-10-30 20:19 UTC, gemantzu commented on gr/lessons/libraries/benchee.md
> +Αυτό συναντάτε συχνά αν οι συναρτήσεις σας δεν περιέχουν κάποιο μέγεθος τυχαιότητας.
συναντάται

2020-10-30 20:20 UTC, gemantzu requested changes
Thank you for all the hard work @RTSolo ! A few typos.

2020-10-30 20:44 UTC, RTSolo commented
Thank you @gemantzu!

2020-10-31 17:03 UTC, gemantzu approved these changes

2020-10-31 17:03 UTC, merged