[GR] Bump (ETS) to latest version
elixirschool/elixirschool pull request #2484
Opened 2020-10-31 10:51 UTC by RTSolo

2020-10-31 14:39 UTC, gemantzu commented on gr/lessons/specifics/ets.md
> +## Συνθήκες Αγώνα
Hm... I don't think we should translate it like this, but to be honest, I don't really know how (or if) we should... @Kosmas / @zorbash any ideas? My instinct tells me we should leave this phrase as is, but some kind of translation might elude me...

2020-10-31 17:21 UTC, gemantzu commented on gr/lessons/specifics/ets.md
> +Για τους μετρητές συγκεκριμένα, [:ets.update_counter/3](http://erlang.org/doc/man/ets.html#update_counter-3) παρέχει για ατομική ενημέρωση-και-ανάγνωση.
Για τους μετρητές συγκεκριμένα, **η** [:ets.update_counter/3](http://erlang.org/doc/man/ets.html#update_counter-3) παρέχει

2020-10-31 17:44 UTC, gemantzu requested changes
Very good @RTSolo, only a typo, but I am still torn about the whole Race Conditions translation.

2020-10-31 18:01 UTC, RTSolo commented
Thank you @gemantzu. Corrected the typo, will be waiting for an update on ## Race Conditions.

2020-11-03 19:25 UTC, gemantzu commented
@RTSolo / @Kosmas / @zorbash let's leave `race conditions` without translation, but if you have any ideas on how to translate it, let me know.

2020-11-03 19:26 UTC, gemantzu approved these changes

2020-11-03 19:26 UTC, merged