[PL] Updated translation for: Concurrency
elixirschool/elixirschool pull request #2573
Opened 2021-05-15 08:24 UTC by bartoszgorka

2021-05-19 14:54 UTC, jangromko requested changes

2021-05-19 14:54 UTC, jangromko commented on pl/lessons/advanced/concurrency.md
> +Czasami nie chcemy by awaria jednego procesu, spowodowała zamknięcie połączonego z nim innego procesu.
```suggestion
Czasami nie chcemy by awaria jednego procesu spowodowała zamknięcie połączonego z nim innego procesu.
```

2021-05-19 14:54 UTC, jangromko commented on pl/lessons/advanced/concurrency.md
> +A co jeżeli nie chcemy łączyć procesów, ale chcemy nadal być informowani o awariach?
```suggestion
A co, jeżeli nie chcemy łączyć procesów, ale chcemy nadal być informowani o awariach?
```

2021-05-19 14:54 UTC, jangromko commented on pl/lessons/advanced/concurrency.md
> +Aktualny stan agenta jest równy ostatniej zwróconej przez agenta wartości:
```suggestion
Aktualny stan agenta jest równy wartości zwracanej przez naszą funkcję:
```

2021-05-19 14:54 UTC, jangromko commented on pl/lessons/advanced/concurrency.md
> +Możemy się do nich odwołać z poziomu innego procesu aplikacji, albo innego węzła.
```suggestion
Możemy się do nich odwołać z poziomu innego procesu aplikacji albo innego węzła.
```

2021-05-20 19:09 UTC, jangromko approved these changes
Looks good, thank you for this PR!

2021-07-20 06:39 UTC, bartoszgorka commented
@doomspork Is it possible to merge it?

2021-07-20 22:52 UTC, merged