Blog: Clean Control Flow in Elixir with Pattern Matching and Immutability
elixirschool/elixirschool pull request #2587
Opened 2021-06-01 16:13 UTC by cristineguadelupe

Create the post file and update the contributors

2021-06-01 16:14 UTC, cristineguadelupe commented
@SophieDeBenedetto Done 😃

2021-06-01 17:41 UTC, SophieDeBenedetto commented
I'll review this week and see if we can get a second set of 👀 on here too! 🚀

2021-06-02 21:34 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +date: 2021-01-06
We'll want to update this date before we publish 😄

2021-06-02 21:34 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +  Learn how to you use pattern matching instead of guard clauses to implement a really clean control flow in Elixir.
change `a really clean` to `really clean`

2021-06-02 21:34 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +It is not my focus to cover everything about pattern matching and immutability on this post. My goal here is to show you how we can use pattern matching instead of guard clauses to implement a really
same thing here, `a really clean` -> `really clean`

2021-06-02 21:37 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +In the first `maybe_attack` function we are calling our player (the first argument) as last_shooter!
I would rephrase this slightly to read something like "We define the first version of the `maybe_attack` function to take in a first _and_ second argument named `last_shooter`. This means the function will only match if the player provided as a first argument matches the player provided as a second argument". Pretty much same thing you are saying here, but just makes the language a little more clear 😄

2021-06-02 21:38 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +As player2 is different from player1, we will not have a valid pattern matching and therefore the elixir will move on to try to match with the next function!
Change "valid pattern matching" to "valid pattern match"

2021-06-02 21:38 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +As player2 is different from player1, we will not have a valid pattern matching and therefore the elixir will move on to try to match with the next function!
change "the elixir" to "Elixir"

2021-06-02 21:39 UTC, SophieDeBenedetto commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +What if player2 tries another attack in a row?
here, wrap "last_shooter" in backtics "``", same with "maybe_attack" and another mention of "last_shooter" below.

2021-06-02 21:40 UTC, SophieDeBenedetto reviewed
This looks great @cristineguadelupe! Very well explained with lots of examples. I left a few comments, mostly minor suggestions to update the wording. Let me know what you think 🚀

2021-06-03 03:42 UTC, cristineguadelupe commented
> This looks great @cristineguadelupe! Very well explained with lots of examples. I left a few comments, mostly minor suggestions to update the wording. Let me know what you think 🚀

Thanks for the proofread and suggestions! ❤️

2021-06-03 22:25 UTC, doomspork requested changes
@cristineguadelupe this is awesome! Like _really_ awesome! I sure hope you'll become a regular contributor to our blog with more great content like this.

Just a few comments but they're fairly minor mostly to do with changing our wording from "you" to "we" in the few places that wasn't already being done.

I did want to ask you and @SophieDeBenedetto your thoughts on perhaps making a few word changes in this to avoid terms that might be upsetting to some given the current atmosphere in the United States. If we could replace `"attack"` with `"move"` and `"shooter"` with `"player"` the concept and game stay the same but use fairly generic game terms. Thoughts?

2021-06-03 22:25 UTC, doomspork commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +Well, we will call our first `maybe_attack` function again and try a match. Player2 wants to make an attack and is also `last_shooter`, so we get the following call
```suggestion
Well, we will call our first `maybe_attack` function again and try a match. Player2 wants to make an attack and is also `last_shooter`, so we get the following call:
```

2021-06-03 22:25 UTC, doomspork commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +Trying to match it with the first maybe_attack function we get the following match
```suggestion
Trying to match it with the first maybe_attack function we get the following match:
```

2021-06-03 22:25 UTC, doomspork commented on _posts/2021-06-01-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> +
What do you think about including a couple sentences here to summarize and wrap up the blog post? Something like:

> That's it! We've learned how pattern matching and data immutability together can provide an elegant solution to control flows, another tool in our Elixir toolbox!

2021-06-03 22:27 UTC, doomspork commented
A few of my comment show "outdated" but they're still applicable, I started these comments before you pushed your changes to those sections for Sophie's feedback 😀

2021-06-05 16:10 UTC, cristineguadelupe commented
> @cristineguadelupe this is awesome! Like _really_ awesome! I sure hope you'll become a regular contributor to our blog with more great content like this.
> 
> Just a few comments but they're fairly minor mostly to do with changing our wording from "you" to "we" in the few places that wasn't already being done.
> 
> I did want to ask you and @SophieDeBenedetto your thoughts on perhaps making a few word changes in this to avoid terms that might be upsetting to some given the current atmosphere in the United States. If we could replace `"attack"` with `"move"` and `"shooter"` with `"player"` the concept and game stay the same but use fairly generic game terms. Thoughts?

Hey Sean, thanks a lot for all the feedback and tips. This is my first post and I certainly hope to contribute more frequently! 😃

2021-06-07 14:00 UTC, SophieDeBenedetto approved these changes
This looks good to me! Thanks for addressing all of the comments @cristineguadelupe 😄 I'll let @doomspork take one last look and then we'll update the publish date and get it out 🚀

2021-06-07 14:46 UTC, doomspork approved these changes
This is awesome! Thank you much @cristineguadelupe and @SophieDeBenedetto. I'll let you update the date and merge when ready.

We can get a tweet setup to go out for this too 🚀

2021-06-07 14:50 UTC, SophieDeBenedetto commented
> This is awesome! Thank you much @cristineguadelupe and @SophieDeBenedetto. I'll let you update the date and merge when ready.
> 
> We can get a tweet setup to go out for this too 🚀

awesome! Actually looks like the publish date is already set to day 🌞 
I'm going to merge and I'll set up a tweet too!

2021-06-07 14:50 UTC, merged

2021-06-07 15:04 UTC, SophieDeBenedetto commented
Post is live here  https://elixirschool.com/blog/clean-control-flow-in-elixir-with-pattern-matching-and-immutability/ with tweet announcement here https://twitter.com/elixirschool/status/1401917723421073413

Thank you @cristineguadelupe 👏 👏 👏