Update Enum.md
elixirschool/elixirschool pull request #2821
Opened 2022-07-23 06:04 UTC by tenshikiri

Bumped to version 1.9.0 + a few extra spaces removed to match lines with en file.

2022-07-23 09:08 UTC, gemantzu commented on lessons/el/basics/enum.md
> +## Περίληψη
Don't change this :)

2022-07-23 09:12 UTC, gemantzu requested changes

2022-07-23 09:12 UTC, gemantzu commented on lessons/el/basics/enum.md
> +## Περίληψη
Don't change this :)

2022-07-23 09:12 UTC, gemantzu commented on lessons/el/basics/enum.md
> +Για να δείτε τις συναρτήσεις στο σύνολό τους επισκεφθείτε τα επίσημα έγγραφα του [`Enum`](https://hexdocs.pm/elixir/Enum.html). Για τεμπέλικη απαρίθμηση (lazy enumeration) χρησιμοποιήστε την ενότητα
We seperate phrases with new lines.

2022-07-23 09:12 UTC, gemantzu commented on lessons/el/basics/enum.md
> +Αυτό μπορεί περαιτέρω να καθαριστεί ορίζοντας την προηγουμένως ανώνυμη συνάρτηση που χρησιμοποιεί τον χειριστή Capture σε μία μεταβλητή και να τη καλλέσει από την `Enum.map/2`.
καλέσει (δες αν το έχουμε με 2 λ και αλλού)

2023-02-05 14:33 UTC, doomspork commented
@gemantzu do you want to bring this across the finish line?

2023-05-09 18:40 UTC, closed without merging