[ru] basics sigils - `1.0.3` -> `1.1.0`
elixirschool/elixirschool pull request #3001
Opened 2024-07-27 07:14 UTC by IgorPolyakov

2024-08-01 10:23 UTC, nscyclone commented on lessons/ru/basics/sigils.md
> +В Elixir 1.15 и выше, идентификаторы строковых меток могут быть последовательностью прописных символов. Это может быть полезно для уточнения назначения строковой метки, предоставляя больше контекста,
```suggestion
В Elixir 1.15 и выше идентификаторы строковых меток могут быть последовательностью прописных символов. Это может быть полезно, чтобы уточнить назначение строковой метки, предоставляя больше контекста, чем один символ.
```

2024-08-01 10:23 UTC, nscyclone commented on lessons/ru/basics/sigils.md
> +Обратите внимание, что для многосимвольных сигилов все символы должны быть прописными. Сигильные функции, такие как sigil_rev или sigil_Rev, вызовут SyntaxError при выполнении.
```suggestion
Обратите внимание, что для многосимвольных строковых меток все символы должны быть прописными. Функции строковых меток, такие как `sigil_rev` или `sigil_Rev`, вызовут `SyntaxError` при выполнении.
```

So far sigils have been called "строковые метки", I'd suggest using this term here for consistency.

2024-08-01 10:24 UTC, nscyclone requested changes
Thanks @IgorPolyakov 
I've added a couple of minor suggestions to your changes, please take a peek.

2024-08-04 08:17 UTC, IgorPolyakov commented
Thanks for the review @nscyclone , I have made the suggested corrections)

2024-08-04 08:21 UTC, IgorPolyakov commented
Thanks for the review @nscyclone, I have made the suggested corrections to enhance readability.

2024-08-05 18:53 UTC, nscyclone approved these changes
Thanks @IgorPolyakov

2024-08-05 18:53 UTC, merged