[ru] intermediate mix_tasks - 1.2.2 -> 1.4.1
elixirschool/elixirschool pull request #3002
Opened 2024-07-27 07:34 UTC by IgorPolyakov

2024-08-01 10:41 UTC, nscyclone commented on lessons/ru/intermediate/mix_tasks.md
> +Mix не запускает наше приложение автоматически или какие-либо его зависимости, что хорошо для многих сценариев использования задач Mix, но что, если нам нужно использовать Ecto и взаимодействовать с
```suggestion
Mix не запускает наше приложение или какие-либо его зависимости автоматически, что хорошо для многих сценариев использования задач Mix. Но что, если нам нужно использовать `Ecto` и взаимодействовать с базой данных?
```

2024-08-01 10:46 UTC, nscyclone requested changes
Thanks @IgorPolyakov 
I'd just like to suggest a minor improvement to enhance readability.

2024-08-04 08:22 UTC, IgorPolyakov commented
Thanks for the review, I have made the suggested corrections to enhance readability.

2024-08-05 18:53 UTC, nscyclone approved these changes
Thanks @IgorPolyakov

2024-08-05 18:53 UTC, merged