[ru] testing bypass - 1.0.0 -> 1.0.1
elixirschool/elixirschool pull request #3004
Opened 2024-07-27 07:53 UTC by IgorPolyakov

2024-08-01 10:39 UTC, nscyclone requested changes
Thanks @IgorPolyakov 
There is a suggestion for a minor syntaxic improvement to the previous version of the lesson.

2024-08-01 10:39 UTC, nscyclone commented on lessons/ru/testing/bypass.md
> +Вместо создания одного `Bypass`-подключения в `setup`, мы создаем два с передачей им портов 1234 и 1337.
```suggestion
Вместо создания одного `Bypass`-подключения в `setup` мы создаем два с передачей им портов 1234 и 1337.
```
Feels like an unnecessary comma missed in the earlier version.

2024-08-04 08:30 UTC, IgorPolyakov commented
Thanks for the review, I have made the suggested syntactic improvements)

2024-08-05 18:53 UTC, nscyclone approved these changes
Thanks @IgorPolyakov

2024-08-05 18:54 UTC, merged